"""Personalized presentation layer for the public intelligence report."""

from __future__ import annotations

import json
from pathlib import Path


PERSONAL_CSS = r"""
<style id="wisdom-signal-theme">
:root{--ink:#172033;--paper:#f4f7fb;--surface:#fff;--blue:#2f6df6;--teal:#168f91;--amber:#e6a238;--muted:#68748a;--line:#dce3ee}
*{box-sizing:border-box}body.personal-intel{margin:0;color:var(--ink);background:linear-gradient(90deg,var(--blue) 0 7px,transparent 7px),var(--paper);font-family:"Yu Gothic UI","Hiragino Sans","Noto Sans CJK SC","Microsoft YaHei UI",sans-serif}
body.personal-intel .reading-progress{height:3px;background:var(--blue)}body.personal-intel .container{max-width:1160px;margin:auto;background:transparent;box-shadow:none}
body.personal-intel .header{position:relative;margin:22px 18px 0;padding:30px 34px 24px;overflow:hidden;border:1px solid #26334d;border-radius:18px 18px 5px 5px;background:var(--ink)!important;box-shadow:0 18px 45px rgba(26,37,59,.12)}
body.personal-intel .header:after{content:"SIGNAL / TOKYO";position:absolute;right:28px;bottom:18px;color:rgba(255,255,255,.08);font:700 34px/1 "Bahnschrift Condensed","Arial Narrow",sans-serif;letter-spacing:.12em;pointer-events:none}
body.personal-intel .header-watermark{display:none}body.personal-intel .header-title{margin:0 0 22px;color:#fff;font-size:clamp(25px,4vw,42px);font-weight:720;letter-spacing:-.04em;text-align:left}
body.personal-intel .signal-eyebrow{display:block;margin-bottom:8px;color:#8facff;font:700 11px/1.2 "Bahnschrift","Arial Narrow",sans-serif;letter-spacing:.2em;text-transform:uppercase}
body.personal-intel .header-info{display:grid;grid-template-columns:repeat(4,minmax(100px,1fr));gap:8px 22px;max-width:760px}body.personal-intel .info-item{align-items:flex-start;text-align:left}body.personal-intel .info-item:nth-child(n+5){display:none}
body.personal-intel .info-label{color:#92a0bb;font-size:11px;letter-spacing:.05em}body.personal-intel .info-value{color:#fff;font:650 15px/1.5 "Bahnschrift","Yu Gothic UI",sans-serif}
body.personal-intel .save-buttons{top:26px;right:28px}body.personal-intel .toggle-wide-btn{display:none}body.personal-intel .toggle-dark-btn,body.personal-intel .save-btn,body.personal-intel .save-dropdown-trigger{border:1px solid rgba(255,255,255,.18);background:rgba(255,255,255,.07);box-shadow:none}
body.personal-intel .signal-admin{display:inline-flex;align-items:center;min-height:34px;padding:0 13px;border:1px solid rgba(255,255,255,.22);border-radius:8px;color:#fff;background:rgba(47,109,246,.28);font-size:12px;font-weight:650;text-decoration:none}body.personal-intel .signal-admin:hover{background:rgba(47,109,246,.48)}
body.personal-intel .signal-brief{position:relative;margin:14px 18px 0;padding:22px 26px 22px 31px;border:1px solid var(--line);border-radius:5px 5px 14px 14px;background:var(--surface)}body.personal-intel .signal-brief:before{content:"";position:absolute;left:0;top:20px;bottom:20px;width:4px;border-radius:0 4px 4px 0;background:var(--blue)}
body.personal-intel .signal-brief-kicker{margin-bottom:7px;color:var(--blue);font:700 11px/1.2 "Bahnschrift",sans-serif;letter-spacing:.16em}body.personal-intel .signal-brief h2{margin:0 0 6px;font-size:20px;letter-spacing:-.02em}body.personal-intel .signal-brief p{margin:0;color:var(--muted);font-size:13px;line-height:1.75}
body.personal-intel .content{margin:0 18px 24px;padding:24px 26px 34px;background:transparent}body.personal-intel .search-bar{margin:0 0 22px}body.personal-intel .search-input{height:43px;border:1px solid var(--line);border-radius:9px;background:rgba(255,255,255,.85);box-shadow:none}
body.personal-intel .rss-section,body.personal-intel .hotlist-section{margin:0 0 28px}body.personal-intel .rss-section-header{margin-bottom:12px;padding:0 0 9px;border-bottom:2px solid var(--ink)}body.personal-intel .rss-section-title{color:var(--ink);font-size:17px;font-weight:720}body.personal-intel .rss-section-count{color:var(--muted)}
body.personal-intel .rss-feeds-grid{display:grid;grid-template-columns:1fr;gap:10px}body.personal-intel .feed-group{padding:15px 17px;border:1px solid var(--line);border-radius:10px;background:var(--surface);box-shadow:none}body.personal-intel .feed-header{border-bottom-color:var(--line)}body.personal-intel .feed-name{color:var(--teal);font-weight:720}
body.personal-intel .rss-item{padding:11px 0;border-radius:0;background:transparent}body.personal-intel .rss-link{color:var(--ink);font-size:14px;line-height:1.55}
body.personal-intel .tab-bar-wrapper{margin:0 0 14px}body.personal-intel .tab-bar{gap:6px}body.personal-intel .tab-btn{border:1px solid var(--line);border-radius:999px;color:var(--muted);background:var(--surface)}body.personal-intel .tab-btn.active{color:#fff;border-color:var(--ink);background:var(--ink)}
body.personal-intel .word-group{position:relative;margin:0 0 12px;overflow:hidden;border:1px solid var(--line);border-radius:10px;background:var(--surface);box-shadow:none}body.personal-intel .word-group:before{content:"";position:absolute;left:0;top:0;bottom:0;width:3px;background:var(--blue)}
body.personal-intel .word-header{padding:15px 18px 13px 21px;background:#f9fbfe}body.personal-intel .word-name{color:var(--ink);font-size:16px;font-weight:720}body.personal-intel .word-count{color:var(--blue)!important}body.personal-intel .word-index{color:#8b96aa;font-family:"Bahnschrift",sans-serif}
body.personal-intel .news-item{margin:0;padding:13px 18px 13px 21px;border:0;border-top:1px solid #edf1f6;border-radius:0;background:transparent;box-shadow:none}body.personal-intel .news-item:hover{background:#f7f9fd;transform:none}body.personal-intel .news-number{color:#8590a4;background:#eef2f8}
body.personal-intel .news-link{color:var(--ink);font-size:14px;line-height:1.55}body.personal-intel .source-name{color:var(--teal)}body.personal-intel .rank-num.top{color:#9b6506;background:#fff2d6}body.personal-intel .section-divider{display:none}body.personal-intel .footer{color:var(--muted);background:transparent}body.personal-intel .fab-bar{opacity:.65}
body.personal-intel.reader-mode .container{max-width:1440px;padding-right:390px;transition:padding-right .25s ease}
body.personal-intel .reader-tabs{position:sticky;top:0;z-index:20;display:flex;align-items:center;gap:4px;margin:0 0 14px;padding:9px;border:1px solid var(--line);border-radius:12px;background:rgba(244,247,251,.94);backdrop-filter:blur(14px)}
body.personal-intel .reader-tab{min-height:34px;padding:0 14px;border:0;border-radius:8px;color:var(--muted);background:transparent;font:650 13px/1 "Yu Gothic UI","Microsoft YaHei UI",sans-serif;cursor:pointer}body.personal-intel .reader-tab:hover{color:var(--ink);background:#e9eef7}body.personal-intel .reader-tab.active{color:#fff;background:var(--ink)}
body.personal-intel .reader-tab-note{margin-left:auto;padding-right:7px;color:#78849a;font-size:12px}
body.personal-intel .signal-language{display:inline-flex;margin-left:8px;padding:2px 6px;border:1px solid #d6deeb;border-radius:5px;color:#718097;background:#f6f8fc;font:700 10px/1.4 "Bahnschrift",sans-serif;vertical-align:2px}
body.personal-intel .signal-open-hint{display:block;margin-top:5px;color:#8792a5;font-size:11px;opacity:0;transform:translateY(-2px);transition:.15s ease}body.personal-intel .rss-item:hover .signal-open-hint,body.personal-intel .news-item:hover .signal-open-hint{opacity:1;transform:none}
body.personal-intel .reading-drawer{position:fixed;z-index:100;top:0;right:0;width:390px;height:100vh;display:flex;flex-direction:column;border-left:1px solid #cfd8e7;background:#fbfcfe;box-shadow:-18px 0 45px rgba(23,32,51,.09);transform:translateX(102%);transition:transform .25s ease}
body.personal-intel.reader-mode .reading-drawer{transform:none}body.personal-intel .drawer-head{display:flex;align-items:center;justify-content:space-between;padding:18px 20px;border-bottom:1px solid var(--line)}body.personal-intel .drawer-label{color:var(--blue);font:750 11px/1 "Bahnschrift",sans-serif;letter-spacing:.14em}body.personal-intel .drawer-close{width:34px;height:34px;border:1px solid var(--line);border-radius:9px;color:var(--muted);background:#fff;font-size:20px;cursor:pointer}
body.personal-intel .drawer-body{overflow:auto;padding:27px 24px 38px}body.personal-intel .drawer-source{margin-bottom:10px;color:var(--teal);font-size:12px;font-weight:700}body.personal-intel .drawer-title{margin:0 0 15px;color:var(--ink);font-size:23px;line-height:1.42;letter-spacing:-.025em}body.personal-intel .drawer-meta{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:24px;color:#78849a;font-size:11px}body.personal-intel .drawer-summary{padding-top:20px;border-top:1px solid var(--line);color:#435069;font-size:14px;line-height:1.9;white-space:pre-line}body.personal-intel .drawer-empty{padding:16px;border-radius:10px;color:#66738a;background:#eef3fa;font-size:13px;line-height:1.7}
body.personal-intel .drawer-actions{display:grid;grid-template-columns:1fr auto;gap:8px;margin-top:26px}body.personal-intel .drawer-original,body.personal-intel .drawer-copy{display:flex;align-items:center;justify-content:center;min-height:43px;border-radius:9px;font-size:13px;font-weight:700;text-decoration:none}body.personal-intel .drawer-original{color:#fff;background:var(--blue)}body.personal-intel .drawer-copy{padding:0 14px;border:1px solid var(--line);color:var(--ink);background:#fff;cursor:pointer}
body.personal-intel .drawer-points{margin:18px 0;padding:17px 18px 10px;border-radius:10px;background:#eef3fa}body.personal-intel .drawer-points strong{display:block;margin-bottom:8px;color:var(--ink);font-size:12px}body.personal-intel .drawer-points li{margin:0 0 8px;color:#45536c;font-size:13px;line-height:1.65}body.personal-intel .drawer-reading{padding-top:20px;border-top:1px solid var(--line);color:#344158;font-size:14px;line-height:1.95;white-space:pre-line}body.personal-intel .drawer-value{margin:20px 0;padding:14px 16px;border-left:3px solid var(--teal);color:#415069;background:#f1f8f8;font-size:13px;line-height:1.75}
body.personal-intel .signal-hidden{display:none!important}body.personal-intel .rss-link,body.personal-intel .news-link{cursor:pointer}
@media(max-width:760px){body.personal-intel{background:var(--paper)}body.personal-intel .header{margin:0;padding:24px 20px 20px;border-radius:0 0 12px 12px}body.personal-intel .header:after{display:none}body.personal-intel .header-title{font-size:28px;margin-bottom:18px}body.personal-intel .header-info{grid-template-columns:repeat(2,minmax(0,1fr))}body.personal-intel .save-buttons{position:static;margin-top:18px;justify-content:flex-start}body.personal-intel .signal-brief{margin:10px 10px 0;padding:18px 18px 18px 23px}body.personal-intel .content{margin:0 10px 18px;padding:20px 0}}
@media(max-width:1050px){body.personal-intel.reader-mode .container{padding-right:0}body.personal-intel .reading-drawer{top:auto;bottom:0;width:100%;height:min(76vh,720px);border-left:0;border-top:1px solid #cfd8e7;border-radius:18px 18px 0 0;transform:translateY(102%)}body.personal-intel.reader-mode .reading-drawer{transform:none}}
@media(prefers-reduced-motion:reduce){body.personal-intel *,body.personal-intel *:before,body.personal-intel *:after{scroll-behavior:auto!important;transition:none!important;animation:none!important}}
</style>
"""


PERSONAL_JS = r"""
<script id="wisdom-signal-script">
document.addEventListener('DOMContentLoaded',function(){
document.body.classList.add('personal-intel');document.title='WISDOM SIGNAL · 个人情报台';
var title=document.querySelector('.header-title');if(title){title.textContent='今日情报信号';var eyebrow=document.createElement('span');eyebrow.className='signal-eyebrow';eyebrow.textContent='WISDOM SIGNAL / PERSONAL BRIEFING';title.prepend(eyebrow)}
var header=document.querySelector('.header');if(header&&!document.querySelector('.signal-brief')){var brief=document.createElement('section');brief.className='signal-brief';brief.innerHTML='<div class="signal-brief-kicker">FOCUS, NOT FEED</div><h2>只保留能影响工作判断的信息</h2><p>优先关注日本 IT 市场、制造业 AI、企业数据平台、云架构与模型工具链。社会热搜和重复事件不再占据第一屏。</p>';header.insertAdjacentElement('afterend',brief)}
var buttons=document.querySelector('.save-buttons');if(buttons&&!buttons.querySelector('.signal-admin')){var admin=document.createElement('a');admin.className='signal-admin';admin.href='http://127.0.0.1:8765/';admin.textContent='管理消息源';admin.title='电脑在线时打开本地管理后台';buttons.prepend(admin)}
document.querySelectorAll('.rss-section-title').forEach(function(el,i){el.textContent=i===0?'最新信号':'订阅来源'});var search=document.querySelector('.search-input');if(search)search.placeholder='搜索今天的有效信号…';
var content=document.querySelector('.content');
if(content){var tabs=document.createElement('nav');tabs.className='reader-tabs';tabs.setAttribute('aria-label','阅读筛选');tabs.innerHTML='<button class="reader-tab active" data-view="all">今日精选</button><button class="reader-tab" data-view="zh">中文内容</button><button class="reader-tab" data-view="intl">国际原文</button><span class="reader-tab-note">点击标题，在站内预览</span>';content.prepend(tabs)}
var drawer=document.createElement('aside');drawer.className='reading-drawer';drawer.setAttribute('aria-label','文章预览');drawer.innerHTML='<div class="drawer-head"><span class="drawer-label">ARTICLE PREVIEW / 文章预览</span><button class="drawer-close" aria-label="关闭预览">×</button></div><div class="drawer-body"><div class="drawer-source">选择一条信号</div><h2 class="drawer-title">标题与摘要会在这里展开</h2><div class="drawer-meta"><span>无需立即离开当前页面</span></div><div class="drawer-empty">先快速判断内容是否值得阅读，再决定是否打开原始文章。</div></div>';document.body.appendChild(drawer);
var enrichedData={};try{var enrichedNode=document.getElementById('wisdom-enriched-data');if(enrichedNode)enrichedData=JSON.parse(enrichedNode.textContent)}catch(ignore){}
function detectLanguage(text){if(/[\u3040-\u30ff]/.test(text))return 'ja';if(/[\u4e00-\u9fff]/.test(text))return 'zh';return 'en'}
var storyLinks=Array.from(document.querySelectorAll('.rss-link,.news-link'));
storyLinks.forEach(function(link){var lang=detectLanguage(link.textContent);link.dataset.lang=lang;var badge=document.createElement('span');badge.className='signal-language';badge.textContent=lang==='zh'?'中文':(lang==='ja'?'日文原文':'英文原文');link.insertAdjacentElement('afterend',badge);var hint=document.createElement('span');hint.className='signal-open-hint';hint.textContent='站内预览 →';badge.insertAdjacentElement('afterend',hint);var row=link.closest('.rss-item,.news-item');if(row)row.dataset.lang=lang;link.removeAttribute('target');link.addEventListener('click',function(event){event.preventDefault();event.stopPropagation();var row=link.closest('.rss-item,.news-item');var summary=row&&row.querySelector('.rss-summary');var source=row&&row.querySelector('.rss-author,.source-name');var meta=row&&row.querySelector('.rss-time,.news-time');var body=drawer.querySelector('.drawer-body');body.innerHTML='<div class="drawer-source"></div><h2 class="drawer-title"></h2><div class="drawer-meta"></div><div class="drawer-summary"></div><div class="drawer-actions"><a class="drawer-original" target="_blank" rel="noopener">阅读原文 ↗</a><button class="drawer-copy">复制链接</button></div>';body.querySelector('.drawer-source').textContent=source?source.textContent.trim():'聚合信号';body.querySelector('.drawer-title').textContent=link.textContent.trim();body.querySelector('.drawer-meta').innerHTML='<span>'+(lang==='zh'?'中文内容':(lang==='ja'?'日文原文':'英文原文'))+'</span>'+(meta?'<span>· '+meta.textContent.trim()+'</span>':'');var summaryBox=body.querySelector('.drawer-summary');if(summary&&summary.textContent.trim()){summaryBox.textContent=summary.textContent.trim()}else{summaryBox.className='drawer-empty';summaryBox.textContent='当前来源只提供标题，没有附带摘要。下一阶段可以由本机 LiteLLM 抽取正文并生成中文摘要；现在仍可安全地打开原文。'}var original=body.querySelector('.drawer-original');original.href=link.href;body.querySelector('.drawer-copy').onclick=function(){navigator.clipboard.writeText(link.href);this.textContent='已复制'};document.body.classList.add('reader-mode');drawer.querySelector('.drawer-close').focus()})});
storyLinks.forEach(function(link){var enriched=enrichedData[link.href];if(!enriched)return;var row=link.closest('.rss-item,.news-item');if(row){row.dataset.lang='zh';row.dataset.hasZh='1'}var hint=link.parentElement&&link.parentElement.querySelector('.signal-open-hint');if(hint)hint.textContent='站内阅读全文 →';var badge=link.parentElement&&link.parentElement.querySelector('.signal-language');if(badge)badge.textContent='AI 中文阅读稿';link.removeAttribute('target');link.addEventListener('click',function(event){event.preventDefault();event.stopPropagation();var row=link.closest('.rss-item,.news-item');var source=row&&row.querySelector('.rss-author,.source-name');var meta=row&&row.querySelector('.rss-time,.news-time');var body=drawer.querySelector('.drawer-body');body.innerHTML='<div class="drawer-source"></div><h2 class="drawer-title"></div><div class="drawer-meta"></div><div class="drawer-summary"></div><div class="drawer-extra"></div><div class="drawer-actions"><a class="drawer-original" target="_blank" rel="noopener">核对原文 ↗</a><button class="drawer-copy">复制链接</button></div>';body.querySelector('.drawer-source').textContent=source?source.textContent.trim():enriched.source;body.querySelector('.drawer-title').textContent=enriched.zh_title||link.textContent.trim();body.querySelector('.drawer-meta').innerHTML='<span>AI 中文阅读稿</span>'+(meta?'<span>· '+meta.textContent.trim()+'</span>':'');body.querySelector('.drawer-summary').textContent=enriched.summary||'';var extra=body.querySelector('.drawer-extra');var points=Array.isArray(enriched.key_points)?enriched.key_points:[];extra.innerHTML=(points.length?'<div class="drawer-points"><strong>关键事实</strong><ul>'+points.map(function(x){return '<li>'+String(x).replace(/</g,'<')+'</li>'}).join('')+'</ul></div>':'')+'<div class="drawer-reading"></div>'+(enriched.why_it_matters?'<div class="drawer-value"></div>':'');extra.querySelector('.drawer-reading').textContent=enriched.reading_text||'';var value=extra.querySelector('.drawer-value');if(value)value.textContent='为什么值得关注：'+enriched.why_it_matters;body.querySelector('.drawer-original').href=link.href;body.querySelector('.drawer-copy').onclick=function(){navigator.clipboard.writeText(link.href);this.textContent='已复制'};document.body.classList.add('reader-mode')})});});
drawer.querySelector('.drawer-close').addEventListener('click',function(){document.body.classList.remove('reader-mode')});document.addEventListener('keydown',function(event){if(event.key==='Escape')document.body.classList.remove('reader-mode')});
document.querySelectorAll('.reader-tab').forEach(function(tab){tab.addEventListener('click',function(){document.querySelectorAll('.reader-tab').forEach(function(x){x.classList.remove('active')});tab.classList.add('active');var view=tab.dataset.view;document.querySelectorAll('.rss-item[data-lang],.news-item[data-lang]').forEach(function(row){row.classList.toggle('signal-hidden',view==='zh'?row.dataset.lang!=='zh':view==='intl'?row.dataset.lang==='zh':false)})})});
});
</script>
"""


def personalize_html(html: str) -> str:
    """Inject the personal report theme into a generated standalone page."""
    if "wisdom-signal-theme" in html:
        return html
    html = html.replace("</head>", f"{PERSONAL_CSS}\n</head>", 1) if "</head>" in html else PERSONAL_CSS + html
    cache_path = Path("site-data/enriched.json")
    enriched_block = ""
    if cache_path.exists():
        try:
            cache = json.loads(cache_path.read_text(encoding="utf-8"))
            articles = cache.get("articles", {})
            # Use json.dumps with ensure_ascii=False and proper HTML escaping via json.dumps itself
            # The browser's JSON.parse handles the content correctly without manual escaping
            payload = json.dumps(articles, ensure_ascii=False, separators=(",", ":"))
            enriched_block = f'<script id="wisdom-enriched-data" type="application/json">{payload}</script>\n'
        except (OSError, ValueError):
            enriched_block = ""
    body_additions = f"{PERSONAL_JS}\n{enriched_block}"
    html = html.replace("</body>", f"{body_additions}</body>", 1) if "</body>" in html else html + body_additions
    return html
